"""
req_analyzer/src/email_sender.py
─────────────────────────────────
Builds a professional HTML email from the analysis dict
and sends it via Gmail SMTP (TLS on port 587).
"""

from __future__ import annotations

import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


# ── HTML template ─────────────────────────────────────────────────────────────

def _section(title: str, emoji: str, items: list[str], color: str) -> str:
    """Render one analysis section as an HTML block."""
    rows = "".join(
        f"""
        <tr>
          <td style="padding:8px 12px;border-bottom:1px solid #f0f0f0;
                     font-size:14px;color:#333;line-height:1.6;">
            <span style="color:{color};font-weight:600;">▸</span>&nbsp;{item}
          </td>
        </tr>"""
        for item in items
    )
    return f"""
    <tr>
      <td style="padding:20px 0 8px 0;">
        <table width="100%" cellpadding="0" cellspacing="0" border="0"
               style="border-radius:8px;overflow:hidden;
                      border:1px solid #e5e5e5;">
          <tr>
            <td style="background:{color};padding:10px 16px;">
              <span style="color:#fff;font-size:15px;font-weight:700;">
                {emoji}&nbsp;&nbsp;{title}
              </span>
            </td>
          </tr>
          {rows}
        </table>
      </td>
    </tr>"""


def build_html_email(project_name: str, analysis: dict) -> str:
    """Return a fully-formed HTML email string."""
    now = datetime.now().strftime("%d %B %Y, %H:%M")

    sections = (
        _section("Functional Requirements",     "⚙️",  analysis["functional_requirements"],     "#2563EB")
        + _section("Non-Functional Requirements","🛡️",  analysis["non_functional_requirements"], "#7C3AED")
        + _section("Risks",                      "⚠️",  analysis["risks"],                      "#DC2626")
        + _section("Assumptions",                "💡",  analysis["assumptions"],                 "#D97706")
        + _section("Questions to Client",        "❓",  analysis["questions_to_client"],         "#059669")
    )

    return f"""
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f4f6f9;font-family:Arial,Helvetica,sans-serif;">

  <!-- Wrapper -->
  <table width="100%" cellpadding="0" cellspacing="0" border="0"
         style="background:#f4f6f9;padding:32px 0;">
    <tr><td align="center">

      <!-- Card -->
      <table width="680" cellpadding="0" cellspacing="0" border="0"
             style="background:#ffffff;border-radius:12px;
                    box-shadow:0 2px 12px rgba(0,0,0,.08);overflow:hidden;">

        <!-- Header -->
        <tr>
          <td style="background:linear-gradient(135deg,#1e3a5f 0%,#2563EB 100%);
                     padding:32px 40px;text-align:center;">
            <p style="margin:0;color:#93c5fd;font-size:12px;
                      letter-spacing:2px;text-transform:uppercase;">
              Requirements Analysis Report
            </p>
            <h1 style="margin:8px 0 4px;color:#ffffff;font-size:26px;">
              {project_name}
            </h1>
            <p style="margin:0;color:#bfdbfe;font-size:13px;">
              Generated on {now}
            </p>
          </td>
        </tr>

        <!-- Body -->
        <tr>
          <td style="padding:24px 40px 8px;">
            <p style="margin:0 0 4px;color:#555;font-size:14px;">Hi Team,</p>
            <p style="margin:0;color:#555;font-size:14px;line-height:1.7;">
              Please find below the AI-generated requirements analysis for
              <strong>{project_name}</strong>. Review each section and let us
              know if you have any feedback.
            </p>
          </td>
        </tr>

        <!-- Sections -->
        <tr>
          <td style="padding:0 40px;">
            <table width="100%" cellpadding="0" cellspacing="0" border="0">
              {sections}
            </table>
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="padding:24px 40px 32px;text-align:center;
                     border-top:1px solid #e5e5e5;margin-top:16px;">
            <p style="margin:0;color:#888;font-size:12px;">
              This report was auto-generated by the Requirements Analyzer tool.<br>
              Please do not reply to this email directly.
            </p>
          </td>
        </tr>

      </table>
      <!-- /Card -->

    </td></tr>
  </table>
</body>
</html>"""


# ── Sender ────────────────────────────────────────────────────────────────────

def send_email(subject: str, html_body: str) -> None:
    """
    Send *html_body* via Gmail SMTP using credentials from the environment.

    Required env vars:
        GMAIL_SENDER       – your Gmail address
        GMAIL_APP_PASSWORD – Gmail App Password (16-char, no spaces needed)
        RECIPIENT_EMAIL    – destination address
    """
    sender   = os.getenv("GMAIL_SENDER")
    password = os.getenv("GMAIL_APP_PASSWORD")
    recipient = os.getenv("RECIPIENT_EMAIL")

    _require_env("GMAIL_SENDER",       sender)
    _require_env("GMAIL_APP_PASSWORD", password)
    _require_env("RECIPIENT_EMAIL",    recipient)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = sender
    msg["To"]      = recipient

    msg.attach(MIMEText(html_body, "html", "utf-8"))

    print(f"📧  Connecting to Gmail SMTP (smtp.gmail.com:587) …")
    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.ehlo()
        server.starttls()
        server.login(sender, password.replace(" ", ""))
        server.sendmail(sender, recipient, msg.as_string())

    print(f"✅  Email sent successfully → {recipient}")


def _require_env(name: str, value) -> None:
    if not value:
        raise EnvironmentError(
            f"Environment variable '{name}' is not set. "
            "Please add it to your .env file."
        )